//======1.========
let a = 5;
let b = ++a;
console.log(a);
console.log(b);


//========2.=====
let q = 5;
let r = q++;
console.log(q);
console.log(r);


//=======3.=======
let n = 20;
console.log(--n);
console.log(n--);
console.log(n);


//========4.======
let x = 8;
console.log(x++);
console.log(++x);
console.log(x);


//=========5.======
let u = 3;
let v = u++ + ++v;
console.log(u);
console.log(v);


//=======6.========
let num = 10;
console.log(num--);
console.log(--num);
console.log(num);
