//========7.======
let w = 2;
let y = ++w + w++;
console.log(w);
console.log(y);


//========8.=======
let c = 7;
console.log(c++);
console.log(c++);
console.log(c);


//========9.========
let m = 4;
let result = m-- + --m;
console.log(m);
console.log(result);


//========10.=======
let d = 1;
console.log(++d + ++d);
console.log(d);


//========11.=======
let o = 6;
let p = --o + o--;
console.log(o);
console.log(p);


//========12.======
let number = 9;
console.log(number++);
console.log(number);
console.log(++number);
